import Head from "next/head";
import { Box } from "@mui/material";
import NavigationUI from "@/components/UI/NavigationUI";
import { SearchUI } from "@/components/UI/SearchUI";
import ProductCard from "@/components/UI/Product/ProductCard";
import classes from "../styles/Home.module.css";
import ProductList from "@/components/UI/Product/ProductList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Khushi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ flexGrow: 1 }}>
          <SearchUI />
          <main>
            <ProductList>
              <ProductCard />
              <ProductCard />
              <ProductCard />
              <ProductCard />
              <ProductCard />
            </ProductList>
          </main>
          <NavigationUI />
        </Box>
      </main>
    </>
  );
}
