import Head from "next/head";
import { Box } from "@mui/material";
import NavigationUI from "@/components/UI/NavigationUI";
import { SearchUI } from "@/components/UI/SearchUI";
import ProductCard from "@/components/Product/ProductCard";
import classes from "../styles/home.module.css";
import ProductList from "@/components/Product/ProductList";
import Layout from "@/components/UI/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Khushi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchUI />
        <Layout>
          <ProductList>
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
            <ProductCard />
          </ProductList>
        </Layout>
        <NavigationUI />
      </main>
    </>
  );
}
