import Head from "next/head";
import { Inter } from "@next/font/google";
import { AppBar, Box, Typography } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ flexGrow: 1 }}>
          <AppBar position="static">
            <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
              News
            </Typography>
          </AppBar>
        </Box>
      </main>
    </>
  );
}
