import React from "react";
import Head from "next/head";
import NavigationUI from "@/components/UI/NavigationUI";
import Register from "@/components/Authentication/Register";
import Layout from "@/components/UI/LayoutUI";
import Login from "@/components/Authentication/Login";

const AuthCard = () => {
  let [showLogin, setShowLogin] = React.useState(true);

  if (showLogin) {
    return <Login setShowLogin={setShowLogin} />;
  } else {
    return <Register setShowLogin={setShowLogin} />;
  }
};

export default function Profile() {
  return (
    <>
      <Head>
        <title>Khushi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <AuthCard />
      </Layout>
      <NavigationUI />
    </>
  );
}
