import Head from "next/head";
import NavigationUI from "@/components/UI/NavigationUI";
import Register from "@/components/Authentication/Register";
import Layout from "@/components/UI/Layout";
import Login from "@/components/Authentication/Login";
import Dashboard from "@/components/User/Dashboard";

export default function Profile() {
  return (
    <>
      <Head>
        <title>Khushi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* <Register /> */}
        {/* <Login /> */}
        <Dashboard />
      </Layout>
      <NavigationUI />
    </>
  );
}
